spring:
  profiles:
    active:
    - smart
    
  thymeleaf:
    cache: false

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  datasource:    url: jdbc:postgresql://localhost:5432/webuniHR
    username: postgres
    password: admin
    
  jpa:    show-sql: true
    hibernate:      ddl-auto: create
    open-in-view: false


logging:
  level:
    org:
      springframework:
        security: DEBUG

  
hr:
  jwtData:
    issuer: HrApp
    alg: HMAC512
    secret: mysecret
    dureation: 1m
  salary:
    def:
      percent: 5
    smart:
      limit1: 1
      limit2: 2.5
      limit3: 5
      percent1: 1
      percent2: 2
      percent3: 5
      limits:
        1: 1
        2.5: 2
        5: 5
        10: 10
        7.5: 8
        
